[build]
  # This is the simple build command.
  command = "next build"

  # This tells Netlify where your final website files are.
  publish = ".next"

[build.environment]
  # This section forces the build to see all your secret keys.
  # This is the key to fixing the missing Google button and the 500 error.
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
  NEXTAUTH_SECRET = "NEXTAUTH_SECRET"
  DATABASE_URL = "DATABASE_URL"
  GEMINI_API_KEY = "GEMINI_API_KEY"
  EMAIL_SERVER_USER = "EMAIL_SERVER_USER"
  EMAIL_SERVER_PASSWORD = "EMAIL_SERVER_PASSWORD"
  NEXTAUTH_URL = "NEXTAUTH_URL"