[build]
  # This is the command that runs when you deploy.
  command = "next build"

  # This tells Netlify where your final website files are.
  publish = ".next"

[build.environment]
  # This section makes sure ALL your secret keys are available during the build.
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
  NEXTAUTH_SECRET = "NEXTAUTH_SECRET"
  DATABASE_URL = "DATABASE_URL"
  GEMINI_API_KEY = "GEMINI_API_KEY"
  EMAIL_SERVER_USER = "EMAIL_SERVER_USER"
  EMAIL_SERVER_PASSWORD = "EMAIL_SERVER_PASSWORD"
  NEXTAUTH_URL = "NEXTAUTH_URL"
