[build]
  # This is the command that runs when you deploy.
  # It sets up the database and then builds your Next.js site.
  command = "npx prisma generate && npx prisma db push && next build"

  # This tells Netlify where your final website files are.
  publish = ".next"

[build.environment]
  # This section lists the names of the environment variables the build needs.
  # The actual secret values are taken from the Netlify UI, not from here.
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
  NEXTAUTH_SECRET = "NEXTAUTH_SECRET"
  DATABASE_URL = "DATABASE_URL"
  GEMINI_API_KEY = "GEMINI_API_KEY"
  EMAIL_SERVER_USER = "EMAIL_SERVER_USER"
  EMAIL_SERVER_PASSWORD = "EMAIL_SERVER_PASSWORD"