[build]
  # ✅ FIX: The command is now just "next build".
  # We already set up the database from your computer, so Netlify doesn't need to.
  command = "next build"

  # This tells Netlify where your final website files are.
  publish = ".next"

[build.environment]
  # This section makes sure your Google Sign-in button appears.
  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
  NEXTAUTH_SECRET = "NEXTAUTH_SECRET"
  DATABASE_URL = "DATABASE_URL"
  GEMINI_API_KEY = "GEMINI_API_KEY"
  EMAIL_SERVER_USER = "EMAIL_SERVER_USER"
  EMAIL_SERVER_PASSWORD = "EMAIL_SERVER_PASSWORD"